services:
  - type: web
    name: langflow
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python src/backend/base/langflow/main.py"
    envVars:
      - key: PORT
        value: 8000
