services:
  - name: langflow
    type: web
    env: python
    buildCommand: ""
    startCommand: "uvicorn src.backend.base.langflow.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: PORT
        value: "8000"

